### ISSUE TITLE
edit the input select component to be compatible with the ant design tab

### ISSUE THREAD

**Issue by gogroup-official** [bpmn-io/dmn-js#755] opened 2023-04-24 14:33 UTC
The problem has been raised here: #615 
can we remove tabindex attribute?
https://github.com/bpmn-io/dmn-js/blob/a4e21ac27a5bbfb87b2b2028218a69a51ee3d1a8/packages/dmn-js-shared/src/components/InputSelect.js#L344

**Comment by nikku** [comment] 2023-04-25 08:31
The last issue was closed (cf. https://github.com/bpmn-io/dmn-js/issues/615#issuecomment-753932431). What shall we do this time to fix it? We believe the issue is within ant-design.

**Comment by gogroup-official** [comment] 2023-04-25 10:30
I tried with a few other libraries like https://github.com/reactjs/react-modal , but also facing the same problem.

**Comment by gogroup-official** [comment] 2023-04-25 10:48
I also tried with MUI modal (https://mui.com/material-ui/react-modal/) and had the same problem. I think that we should to do something.

**Comment by nikku** [comment] 2023-04-25 12:06
Re-opened https://github.com/bpmn-io/dmn-js/issues/615, and will close this issue as a duplicate.

**Closed by nikku** 2023-04-25 12:06 UTC
Labels: needs more information
