### ISSUE TITLE
Hit Policy Not Closed on Cell Click

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#546] opened 2020-07-15 18:43 UTC
__Describe the Bug__

![15-07-_2020_20-40-20](https://user-images.githubusercontent.com/7633572/87582946-7ae22580-c6db-11ea-9801-54e9b91ed3a4.gif)

__Steps to Reproduce__

1. Click Hit Policy to open dropdown
2. Click a cell

__Expected Behavior__

Dropdown should close on click outside of dropdown.

__Environment__

 - Library version: 9

**Comment by barmac** [comment] 2020-07-31 07:06
I could reproduce this bug only when I clicked on cells. So it seems that at some point we stop event propagation so that it's not handled by InputSelect's global click listener.

**Comment by barmac** [comment] 2020-07-31 07:20
Found it: https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-decision-table/src/features/cell-selection/CellSelection.js#L70

So CellSelection stop events propagation and because of that event does not bubble up to `document`. Therefore, `click` handler set up by `InputSelect` is not triggered and `InputSelect` is not closed as a result.

**Comment by philippfromme** [comment] 2020-07-31 07:39
Damn! 🔥 🚒

**Comment by barmac** [comment] 2020-07-31 10:15
@philippfromme Would you expect the dropdown to close when user:
* adds a column,
* adds a rule,
* uses drag and drop feature,
* resizes column?

![click](https://user-images.githubusercontent.com/28307541/89025560-5c109f80-d327-11ea-937d-b8efdfec8f83.gif)

**Comment by barmac** [comment] 2020-07-31 11:03
I would expect the select to close immediately when you start interaction with other components.

**Comment by philippfromme** [comment] 2020-07-31 12:06
I'd expect the dropdown to close whenever there is mouse interaction outside of it.

**Comment by barmac** [comment] 2020-07-31 12:13
I created https://github.com/bpmn-io/dmn-js/issues/559 for that.

**Closed** 2020-08-05 13:55 UTC
Labels: bug, needs review
