### ISSUE TITLE
dragging of rows incorrectly previewed

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/dmn-js#550] opened 2020-07-27 14:29 UTC
__Describe the Bug__

The dragging of rows in dmn tables works but is incorrectly formatted during the dragging process

__Steps to Reproduce__

1. Create two or more decision rows
2. Drag them by using the "drag" icon
![dmn_drag_broken](https://user-images.githubusercontent.com/42800119/88554040-48fb8800-d026-11ea-8414-4850c4f72368.gif)

__Expected Behavior__

Visual during dragging is the same as the end result

__Environment__

Please complete the following information:

 - Browser: n/a
 - Modeler: 4.1.1
 - OS: Arch Linux (Manjaro)
 - Library version: as used in 4.1.1 modeler

**Comment by barmac** [comment] 2020-07-30 13:52
I looked into that and in fact there are two problems:
* incorrectly displayed line showing dragging target, which can be noticed in the [staging environment](https://bpmn-io-demo-staging.herokuapp.com/dmn/s/check-order) -> vanilla dmn-js,
* broken layout which is caused by class clashes between Camunda Modeler and dmn-js (`.bottom` and `.top`).

While the first issue is still to be investigated, the second can be fixed quite easily by renaming classes.

**Comment by barmac** [comment] 2020-07-30 15:01
So while the second issue is fixed in Camunda Modeler via https://github.com/camunda/camunda-modeler/issues/1899, the first one was broken by removal of `position: relative` for all table cells which was a fix for incorrect bottom border of the table: https://github.com/bpmn-io/dmn-js/pull/541. I gotta find some workaround. Maybe we should just display the feedback in a different way.

**Comment by barmac** [comment] 2020-07-31 09:07
Closed via https://github.com/bpmn-io/dmn-js/pull/557

**Closed by barmac** 2020-07-31 09:07 UTC
Labels: bug, needs review
