### ISSUE TITLE
Bug when opening a local file

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#94] opened 2016-09-26 12:15 UTC
When you open a local file, for example 3 times, a div class "tjs-controls" is created 3 times as well:

![screen shot 2016-09-26 at 14 11 53](https://cloud.githubusercontent.com/assets/3993987/18833916/6748c332-83f3-11e6-8f23-5cc7044773e1.png)

**Comment by SebastianStamm** [comment] 2016-09-27 09:36
Thanks for reporting. I added this bug to our backlog. 

I can confirm the bug, but don't see any decrease in functionality. Is there any feature that is broken because of this?

If you want to and know how to fix it, you can always provide a pull request ;)

**Comment by SebastianStamm** [comment] 2016-10-24 12:49
Should be fixed in the latest release of dmn-js and table-js. Commit that fixed it is https://github.com/bpmn-io/table-js/commit/7db07ca1cec6323d5aebc6592eceb7f13ff9716d

**Closed by SebastianStamm** 2016-10-24 12:49 UTC
Labels: bug
