### ISSUE TITLE
Bundled (compiled) 1.2.2

### ISSUE THREAD

**Issue by eugene-moroz** [bpmn-io/dmn-js#278] opened 2018-01-05 10:30 UTC
Might be related to https://forum.bpmn.io/t/dmn-js-1-1-1-usage/1969/5.

If understand correctly, there is a way to get bundled version of dmn-js, e.g. by executing as `grunt` task `tasks/bundle.js`. That doesn't seem to work anymore because since version 1, you guys switched from ES2015 to ES6. We would need it because to compile/bundle dmn-js with whatever configuration consumer has (different webpack, babel or browserify) doesn't sound like a solution which will stable. Could you maybe advise of any way to make that work? I tried bare minimum Gruntfile and to include babelify but that doesn't seem to work.
```
// Gruntfile
'use strict';
module.exports = function(grunt) {
  require('load-grunt-tasks')(grunt);
  require('./tasks/bundle.js')(grunt);
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    bundle: {
      data: {
        name: 'dmn-js',
        dest: 'dist',
        src: 'packages/dmn-js',
      }
    }

  });
  grunt.registerTask('default', [ 'bundle' ]);
};
```
and
```
//tasks/bundle.js
browserify(browserifyOptions)
      .transform('babelify', {
        'presets': ['env']
      })
      .plugin(derequire)
      .plugin(collapse)
      .add(src)
      .bundle(function(err, result) {
```

**Comment by nikku** [comment] 2018-01-05 12:44
This is a duplicate of https://github.com/bpmn-io/dmn-js/issues/277. 

We'll publish pre-built versions of `dmn-js` once we reach stability and feature parity on the `1.x` branch.

**Closed by nikku** 2018-01-05 12:44 UTC

**Comment by nikku** [comment] 2018-01-05 12:45
The snippet for bundling with browserify you've added looks good, what exactly breaks for you when executing it?

**Comment by eugene-moroz** [comment] 2018-01-05 12:46
Was trying to fix this (it still occurs)
```
Running "bundle:data" (bundle) task
bundled [937ms]
Warning: 'import' and 'export' may appear only with 'sourceType: module' Use --force to continue.

Aborted due to warnings.
```

**Comment by nikku** [comment] 2018-01-05 12:48
Must be a transform that gets ES6 code while expecting ES5.

**Comment by eugene-moroz** [comment] 2018-01-05 12:52
Sounds like `browserify` issue, right?

**Comment by nikku** [comment] 2018-01-05 13:41
Sounds like a configuration issue to me :wink:. We'll look into this in a little while.
