### ISSUE TITLE
Bug: dmn-js from 2.0.0 to 4.3.0 using AngularJS 1.6

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/dmn-js#356] opened 2018-05-13 16:27 UTC
The last version that WORKS with AngularJS 1.6 is dmn-js 1.5.1 without any problem using the pre-packaged versions, always.

But upgrading to a new version, ALL the new versions from 2.0.0 to 4.3.0 dmn-js DON'T WORK if I try to add a rule.

### Steps to follow to reproduce the error

If I click to add a rule using the last version (dmn-js 4.3.0):
![screen shot 2018-05-13 at 18 20 43](https://user-images.githubusercontent.com/3993987/39969325-69f4b800-56da-11e8-864f-128aa3e4074e.png)

It shows a lot of warnings about "too much recursions":
![screen shot 2018-05-13 at 18 14 25](https://user-images.githubusercontent.com/3993987/39969272-91e55b36-56d9-11e8-8c5f-8687bdb86c88.png)

It interferes with the events of dmn-js (line: 30018):
![screen shot 2018-05-13 at 18 20 17](https://user-images.githubusercontent.com/3993987/39969334-7edf4820-56da-11e8-99e0-7f20bf44e9e1.png)

And the events of the AngularJS (line: 3767):
![screen shot 2018-05-13 at 18 18 38](https://user-images.githubusercontent.com/3993987/39969309-1a814f54-56da-11e8-8b36-542303bb2d88.png)

**Comment by nikku** [comment] 2018-05-14 08:42
We were not able to reproduce this issue against AngularJS `v1.2.29`. Seems like this issue is specific to newer Angular versions only. 

Could you provide us with the necessary failing test cases?

**Comment by rbatllet** [comment] 2018-05-14 08:45
Tested with AngularJS 1.5 and AngularJS 1.6

**Comment by philippfromme** [comment] 2018-05-14 08:46
This is an issue with [Inferno](https://github.com/infernojs/inferno) which we use in dmn-js. The `stopPropagation` function is used by Inferno.

**Comment by rbatllet** [comment] 2018-05-14 08:49
dmn-js 1.5.1 works perfectly. The next version 2.0.0 and up doesn't.

**Comment by nikku** [comment] 2018-05-14 09:00
@philippfromme May be fixed with [`inferno@5.0.5`](https://github.com/infernojs/inferno/releases/tag/v5.0.5). Could you verify this?

**Comment by rbatllet** [comment] 2018-05-14 09:36
dmn-js is already using inferno 5.0.5

![screen shot 2018-05-14 at 11 34 57](https://user-images.githubusercontent.com/3993987/39989685-e9a5ea02-576a-11e8-9ee6-23aa4200b4e2.png)

and still does not work.

**Comment by nikku** [comment] 2018-05-14 13:07
Published `dmn-js@4.3.1` with `inferno@5.0.5` inside.

**Closed by nikku** 2018-05-14 13:07 UTC
Labels: bug, ready

**Comment by rbatllet** [comment] 2018-05-14 15:43
Solved, finally. Thank you very much!
